
library(data.table)
library(flextable)
library(tidyverse)
library(checkmate)
library(patchwork)
library(ggplot2)
library(readxl)
library(mice)

library(mlr3benchmark)
library(mlr3pipelines)
library(mlr3learners)
library(mlr3filters)
library(mlr3tuning)
library(mlr3viz)
library(precrec)
library(paradox)
library(praznik)
library(caret)
library(kknn)
library(mlr3)

library(chemometrics)
library(prospectr)
library(signal)
library(utils)
library(purrr)
